# Generated by Django 5.2.5 on 2025-08-28 09:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tc_id_back',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.tcid_upload_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='tc_id_front',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.tcid_upload_path),
        ),
    ]
