# Generated by Django 5.2.5 on 2025-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_tc_id_back_profile_tc_id_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0, help_text='0 ile 5 arasında puan'),
        ),
    ]
