# Generated by Django 5.2.5 on 2025-08-27 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=64)),
                ('year', models.PositiveIntegerField()),
                ('engine', models.CharField(blank=True, max_length=64)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Benzin'), ('diesel', 'Dizel'), ('hybrid', 'Hybrid'), ('electric', 'Elektrik')], default='gasoline', max_length=16)),
                ('transmission', models.CharField(choices=[('manual', 'Düz'), ('automatic', 'Otomatik')], default='automatic', max_length=16)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_text', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_photos/')),
                ('is_cover', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car')),
            ],
        ),
    ]
