# Generated by Django 5.2.5 on 2025-08-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='carphoto',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='carphoto',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
