# Generated by Django 5.2.5 on 2025-08-28 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_options_alter_carphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('cabrio', 'Cabrio'), ('wagon', 'Station Wagon'), ('pickup', 'Pickup'), ('van', 'Van'), ('mpv', 'MPV/Minivan')], default='sedan', max_length=16),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('white', 'Beyaz'), ('black', 'Siyah'), ('gray', 'Gri'), ('silver', 'Gümüş'), ('blue', 'Mavi'), ('red', 'Kırmızı'), ('green', 'Yeşil'), ('brown', 'Kahverengi'), ('beige', 'Bej'), ('yellow', 'Sarı'), ('orange', 'Turuncu')], default='white', max_length=16),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_cc',
            field=models.PositiveIntegerField(blank=True, help_text='Motor hacmi (cc)', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='listing_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='car',
            name='power_hp',
            field=models.PositiveIntegerField(blank=True, help_text='Motor gücü (HP)', null=True),
        ),
    ]
