# Generated by Django 5.2.5 on 2025-08-28 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_body_type_car_color_car_engine_cc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(blank=True, max_length=100, verbose_name='Versiyon Adı')),
                ('segment', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('S', 'S (Spor/Lüks)')], max_length=2, verbose_name='Segment')),
                ('power_kw', models.PositiveIntegerField(blank=True, null=True, verbose_name='Güç (kW)')),
                ('torque_nm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tork (Nm)')),
                ('drive_type', models.CharField(blank=True, choices=[('FWD', 'Önden Çekiş (FWD)'), ('RWD', 'Arkadan İtiş (RWD)'), ('AWD', '4x4 / AWD')], max_length=3, verbose_name='Çekiş')),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Boş Ağırlık (kg)')),
                ('max_weight_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimum Ağırlık (kg)')),
                ('top_speed_kmh', models.PositiveIntegerField(blank=True, null=True, verbose_name='Son Sürat (km/s)')),
                ('accel_0_100_s', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='0-100 (sn)')),
                ('co2_g_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='CO₂ (g/km)')),
                ('cylinders', models.PositiveIntegerField(blank=True, null=True, verbose_name='Silindir Sayısı')),
                ('valves', models.PositiveIntegerField(blank=True, null=True, verbose_name='Valf Sayısı')),
                ('turbo', models.BooleanField(default=False, verbose_name='Turbo')),
                ('cons_city', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Yakıt (Şehir İçi) Lt/100km')),
                ('cons_highway', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Yakıt (Şehir Dışı) Lt/100km')),
                ('cons_combined', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Yakıt (Ortalama) Lt/100km')),
                ('wheelbase_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dingil Mesafesi (mm)')),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Uzunluk (mm)')),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Genişlik (mm)')),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yükseklik (mm)')),
                ('trunk_l', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bagaj Kapasitesi (L)')),
                ('doors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kapı Sayısı')),
                ('tire_size', models.CharField(blank=True, max_length=50, verbose_name='Lastik Boyutları')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='cars.car')),
            ],
            options={
                'verbose_name': 'Teknik Özellik',
                'verbose_name_plural': 'Teknik Özellikler',
            },
        ),
    ]
