# Generated by Django 5.2.5 on 2025-08-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carspecs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs', models.BooleanField(default=False)),
                ('esp_vsa', models.BooleanField(default=False)),
                ('bas', models.BooleanField(default=False)),
                ('child_lock', models.BooleanField(default=False)),
                ('airbag_driver', models.BooleanField(default=False)),
                ('airbag_passenger', models.BooleanField(default=False)),
                ('isofix', models.BooleanField(default=False)),
                ('blind_spot', models.BooleanField(default=False)),
                ('night_vision', models.BooleanField(default=False)),
                ('lane_assist', models.BooleanField(default=False)),
                ('central_lock', models.BooleanField(default=False)),
                ('hill_assist', models.BooleanField(default=False)),
                ('fatigue_detection', models.BooleanField(default=False)),
                ('hydraulic_steering', models.BooleanField(default=False)),
                ('electric_windows', models.BooleanField(default=False)),
                ('climate', models.BooleanField(default=False)),
                ('heated_seats', models.BooleanField(default=False)),
                ('memory_seats', models.BooleanField(default=False)),
                ('ventilated_seats', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('cooled_glovebox', models.BooleanField(default=False)),
                ('trip_computer', models.BooleanField(default=False)),
                ('start_stop', models.BooleanField(default=False)),
                ('rear_camera', models.BooleanField(default=False)),
                ('electric_mirrors', models.BooleanField(default=False)),
                ('heated_mirrors', models.BooleanField(default=False)),
                ('adaptive_headlights', models.BooleanField(default=False)),
                ('park_front', models.BooleanField(default=False)),
                ('park_rear', models.BooleanField(default=False)),
                ('sunroof', models.BooleanField(default=False)),
                ('panoramic_roof', models.BooleanField(default=False)),
                ('smart_trunk', models.BooleanField(default=False)),
                ('power_tailgate', models.BooleanField(default=False)),
                ('tow_hook', models.BooleanField(default=False)),
                ('android_auto', models.BooleanField(default=False)),
                ('apple_carplay', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('usb_aux', models.BooleanField(default=False)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.car')),
            ],
            options={
                'verbose_name': 'Donanım',
                'verbose_name_plural': 'Donanımlar',
            },
        ),
    ]
