# Generated by Django 5.2.5 on 2025-08-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carfeatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carfeatures',
            name='adaptive_headlights',
        ),
        migrations.RemoveField(
            model_name='carfeatures',
            name='electric_mirrors',
        ),
        migrations.RemoveField(
            model_name='carfeatures',
            name='heated_mirrors',
        ),
        migrations.RemoveField(
            model_name='carfeatures',
            name='park_front',
        ),
        migrations.RemoveField(
            model_name='carfeatures',
            name='park_rear',
        ),
        migrations.RemoveField(
            model_name='carfeatures',
            name='power_tailgate',
        ),
        migrations.RemoveField(
            model_name='carfeatures',
            name='smart_trunk',
        ),
        migrations.AddField(
            model_name='carfeatures',
            name='alloy_wheels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carfeatures',
            name='auto_park',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carfeatures',
            name='fog_lights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carfeatures',
            name='headlight_washers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carfeatures',
            name='led_headlights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carfeatures',
            name='led_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carfeatures',
            name='park_sensor_front',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carfeatures',
            name='park_sensor_rear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carfeatures',
            name='roof_rails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carfeatures',
            name='xenon_led',
            field=models.BooleanField(default=False),
        ),
    ]
