# Generated by Django 5.2.5 on 2025-08-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_carfeatures_adaptive_headlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Enlem (örn: 41.0082)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Boylam (örn: 28.9784)', max_digits=9, null=True),
        ),
    ]
