# Generated by Django 5.2.5 on 2025-08-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_latitude_car_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='car',
            name='district',
            field=models.CharField(blank=True, max_length=64, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='car',
            name='kilometers',
            field=models.PositiveIntegerField(default=0, verbose_name='KM'),
        ),
        migrations.AlterField(
            model_name='car',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Günlük Fiyat (₺)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location_text',
            field=models.CharField(max_length=255, verbose_name='Adres/Konum'),
        ),
    ]
