# Generated by Django 5.2.5 on 2025-08-30 13:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_city_car_district_car_kilometers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='Günlük Fiyat (₺)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
