# Generated by Django 5.2.5 on 2025-09-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_daily_price_alter_car_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='damage_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='car',
            name='damage_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hasar Notu'),
        ),
    ]
