# Generated by Django 5.2.5 on 2025-09-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_damage_json_car_damage_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='damage_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Boya/Parça Durumu'),
        ),
        migrations.AlterField(
            model_name='car',
            name='damage_note',
            field=models.TextField(blank=True, verbose_name='Hasar Notu'),
        ),
    ]
