# cars/brand_data.py

BRANDS = [
    ("", "Marka seçin"),
    ("Audi", "Audi"),
    ("BMW", "BMW"),
    ("Mercedes-Benz", "Mercedes-Benz"),
    ("Volkswagen", "Volkswagen"),
    ("Renault", "Renault"),
    ("Fiat", "Fiat"),
    ("Ford", "Ford"),
    ("Hyundai", "Hyundai"),
    ("Toyota", "Toyota"),
    ("Peugeot", "Peugeot"),
    ("Opel", "Opel"),
    ("Citroën", "Citroën"),
    ("Volvo", "Volvo"),
    ("Nissan", "Nissan"),
    ("Honda", "Honda"),
    ("Kia", "Kia"),
    ("SEAT", "SEAT"),
    ("Škoda", "Škoda"),
    ("Porsche", "Porsche"),
    ("Dacia", "Dacia"),
]

MODELS = {
    "Audi": ["A1", "A3", "A4", "A5", "A6", "Q2", "Q3", "Q5", "Q7", "Q8", "TT"],
    "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X6", "Z4"],
    "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "E-Class", "S-Class", "GLA", "GLC", "GLE", "GLS", "CLA"],
    "Volkswagen": ["Golf", "Polo", "Passat", "Tiguan", "T-Roc", "Touran", "Jetta"],
    "Renault": ["Clio", "Megane", "Talisman", "Captur", "Kadjar", "Symbol"],
    "Fiat": ["Egea", "Panda", "500", "Doblo", "Tipo"],
    "Ford": ["Fiesta", "Focus", "Mondeo", "Kuga", "Puma"],
    "Hyundai": ["i10", "i20", "i30", "Elantra", "Tucson", "Kona"],
    "Toyota": ["Yaris", "Corolla", "Auris", "C-HR", "RAV4"],
    "Peugeot": ["208", "308", "508", "2008", "3008", "5008"],
    "Opel": ["Corsa", "Astra", "Insignia", "Mokka"],
    "Citroën": ["C3", "C4", "C5 Aircross", "Berlingo"],
    "Volvo": ["S60", "S90", "V40", "XC40", "XC60", "XC90"],
    "Nissan": ["Micra", "Qashqai", "Juke", "X-Trail"],
    "Honda": ["Civic", "Accord", "CR-V", "HR-V", "Jazz"],
    "Kia": ["Rio", "Ceed", "Sportage", "Sorento"],
    "SEAT": ["Ibiza", "Leon", "Ateca", "Arona"],
    "Škoda": ["Fabia", "Octavia", "Superb", "Karoq", "Kodiaq"],
    "Porsche": ["911", "Cayman", "Boxster", "Cayenne", "Macan", "Panamera", "Taycan"],
    "Dacia": ["Sandero", "Logan", "Duster", "Jogger"],
}

# Alt model / varyant listeleri (marka → model → varyantlar)
VARIANTS = {
    "BMW": {
        "1 Series": ["114i", "116i", "118i", "120i", "M135i"],
        "2 Series": ["218i", "220i", "M235i", "M240i"],
        "3 Series": ["316i", "318i", "320i", "330i", "M3"],
        "4 Series": ["420i", "420d", "430i", "430d", "M4"],
        "5 Series": ["520i", "530i", "520d", "530d", "M5"],
        "7 Series": ["730i", "740i", "750i"],
        "X1": ["18i", "20i", "20d"],
        "X3": ["20i", "30i", "30d", "M40i"],
        "X5": ["30d", "40i", "M50i"],
        "X6": ["30d", "40i", "M Competition"],
        "Z4": ["sDrive20i", "sDrive30i", "M40i"],
    },
    "Toyota": {
        "Yaris": ["1.0", "1.5", "Hybrid"],
        "Corolla": ["1.6", "1.5", "Hybrid"],
        "Auris": ["1.33", "1.6", "Hybrid"],
        "C-HR": ["1.8 Hybrid", "2.0 Hybrid"],
        "RAV4": ["2.0", "2.5 Hybrid", "PHEV"],
    },
    "Renault": {
        "Clio": ["1.0 TCe", "1.3 TCe", "1.5 dCi"],
        "Megane": ["1.3 TCe", "1.5 dCi"],
        "Talisman": ["1.6 dCi", "1.3 TCe"],
        "Captur": ["1.3 TCe", "1.5 dCi", "E-Tech Hybrid"],
        "Kadjar": ["1.3 TCe", "1.5 dCi"],
        "Symbol": ["1.0", "1.5 dCi"],
    },
    "Mercedes-Benz": {
        "A-Class": ["A180", "A200", "A250", "AMG A35"],
        "B-Class": ["B180", "B200"],
        "C-Class": ["C180", "C200", "C300", "AMG C43"],
        "E-Class": ["E200", "E220d", "E300"],
        "S-Class": ["S350d", "S450", "S500"],
        "GLA": ["200", "220d", "AMG 35"],
        "GLC": ["200", "220d", "300e"],
        "GLE": ["300d", "350d", "450"],
        "GLS": ["400d", "580"],
        "CLA": ["180", "200", "AMG 35"],
    },
    "Volkswagen": {
        "Golf": ["1.0 TSI", "1.5 TSI", "2.0 GTI", "2.0 TDI"],
        "Polo": ["1.0 MPI", "1.0 TSI"],
        "Passat": ["1.5 TSI", "2.0 TDI"],
        "Tiguan": ["1.5 TSI", "2.0 TDI"],
        "T-Roc": ["1.0 TSI", "1.5 TSI"],
        "Touran": ["1.5 TSI", "2.0 TDI"],
        "Jetta": ["1.4 TSI", "2.0 TDI"],
    },
    "Audi": {
        "A1": ["25 TFSI", "30 TFSI"],
        "A3": ["30 TFSI", "35 TFSI", "1.6 TDI", "S3"],
        "A4": ["35 TFSI", "40 TFSI", "40 TDI", "S4"],
        "A5": ["40 TFSI", "45 TFSI", "S5"],
        "A6": ["40 TDI", "45 TFSI"],
        "Q2": ["30 TFSI", "35 TFSI"],
        "Q3": ["35 TFSI", "40 TFSI"],
        "Q5": ["40 TDI", "45 TFSI"],
        "Q7": ["45 TDI", "55 TFSI"],
        "Q8": ["50 TDI", "55 TFSI", "SQ8"],
        "TT": ["40 TFSI", "TTS"],
    },
    "Fiat": {
        "Egea": ["1.3 MJet", "1.6 MJet", "1.4 Fire", "1.5 T4"],
        "Panda": ["1.0", "1.2"],
        "500": ["1.0", "1.2", "Electric"],
        "Doblo": ["1.3 MJet", "1.6 MJet"],
        "Tipo": ["1.3 MJet", "1.6 MJet"],
    },
    "Ford": {
        "Fiesta": ["1.0 EcoBoost", "1.1"],
        "Focus": ["1.0 EcoBoost", "1.5 TDCi"],
        "Mondeo": ["1.5 EcoBoost", "2.0 TDCi"],
        "Kuga": ["1.5 EcoBoost", "2.0 EcoBlue", "PHEV"],
        "Puma": ["1.0 EcoBoost", "Hybrid"],
    },
    "Hyundai": {
        "i10": ["1.0", "1.2"],
        "i20": ["1.0 T-GDI", "1.4"],
        "i30": ["1.4 T-GDI", "1.6 CRDi"],
        "Elantra": ["1.6 MPI", "1.6 CRDi"],
        "Tucson": ["1.6 T-GDI", "1.6 CRDi", "Hybrid"],
        "Kona": ["1.0 T-GDI", "Electric"],
    },
    "Peugeot": {
        "208": ["1.2 PureTech", "Electric"],
        "308": ["1.2 PureTech", "1.5 BlueHDi"],
        "508": ["1.6 PureTech", "1.5 BlueHDi"],
        "2008": ["1.2 PureTech", "Electric"],
        "3008": ["1.2 PureTech", "1.5 BlueHDi", "Hybrid"],
        "5008": ["1.2 PureTech", "1.5 BlueHDi"],
    },
    "Opel": {
        "Corsa": ["1.2", "1.2 Turbo", "Electric"],
        "Astra": ["1.2 Turbo", "1.5 D"],
        "Insignia": ["1.5 Turbo", "2.0 D"],
        "Mokka": ["1.2 Turbo", "Electric"],
    },
    "Citroën": {
        "C3": ["1.2 PureTech", "1.5 BlueHDi"],
        "C4": ["1.2 PureTech", "Electric"],
        "C5 Aircross": ["1.6 PureTech", "1.5 BlueHDi", "Hybrid"],
        "Berlingo": ["1.5 BlueHDi"],
    },
    "Volvo": {
        "S60": ["T4", "T5", "B5"],
        "S90": ["T5", "B5", "Recharge"],
        "V40": ["T3", "D3"],
        "XC40": ["T3", "B4", "Recharge"],
        "XC60": ["B5", "Recharge"],
        "XC90": ["B5", "Recharge"],
    },
    "Nissan": {
        "Micra": ["1.0"],
        "Qashqai": ["1.3 DIG-T", "1.5 dCi", "e-POWER"],
        "Juke": ["1.0 DIG-T"],
        "X-Trail": ["1.5 e-POWER", "1.6 dCi"],
    },
    "Honda": {
        "Civic": ["1.6", "1.5 VTEC Turbo", "e:HEV"],
        "Accord": ["1.5 VTEC Turbo", "Hybrid"],
        "CR-V": ["1.5 VTEC Turbo", "Hybrid"],
        "HR-V": ["1.5", "Hybrid"],
        "Jazz": ["1.3", "Hybrid"],
    },
    "Kia": {
        "Rio": ["1.2", "1.0 T-GDI"],
        "Ceed": ["1.0 T-GDI", "1.5 T-GDI"],
        "Sportage": ["1.6 T-GDI", "1.6 CRDi", "Hybrid"],
        "Sorento": ["2.2 CRDi", "Hybrid", "PHEV"],
    },
    "SEAT": {
        "Ibiza": ["1.0 MPI", "1.0 TSI"],
        "Leon": ["1.0 eTSI", "1.5 TSI", "2.0 TDI"],
        "Ateca": ["1.5 TSI", "2.0 TDI"],
        "Arona": ["1.0 TSI"],
    },
    "Škoda": {
        "Fabia": ["1.0 MPI", "1.0 TSI"],
        "Octavia": ["1.0 eTSI", "1.5 TSI", "2.0 TDI"],
        "Superb": ["1.5 TSI", "2.0 TDI", "PHEV"],
        "Karoq": ["1.5 TSI", "2.0 TDI"],
        "Kodiaq": ["1.5 TSI", "2.0 TDI"],
    },
    "Porsche": {
        "911": ["Carrera", "Carrera S", "Turbo"],
        "Cayman": ["2.0", "S"],
        "Boxster": ["2.0", "S"],
        "Cayenne": ["3.0", "Turbo", "Hybrid"],
        "Macan": ["2.0", "S", "GTS"],
        "Panamera": ["4", "4S", "Turbo", "Hybrid"],
        "Taycan": ["RWD", "4S", "Turbo"],
    },
    "Dacia": {
        "Sandero": ["1.0", "1.0 TCe", "LPG"],
        "Logan": ["1.0", "1.5 dCi"],
        "Duster": ["1.3 TCe", "1.5 dCi", "4x4"],
        "Jogger": ["1.0 TCe", "Hybrid"],
    },
}
